#!/usr/bin/perl

# had to not use -T taint check because of taint errors with $cipher->crypt($buf) on about line 434

use strict;
use warnings;
use Backup::ZFSonAWS;

$ENV{'PATH'} = '/bin:/usr/bin:/sbin:/usr/local/bin';
delete @ENV{'IFS', 'CDPATH', 'ENV', 'BASH_ENV'};



my $options = Backup::ZFSonAWS::get_options(@ARGV);
require Data::Dumper;
my $xo = Data::Dumper::Dumper($options);
print STDERR "XO=".$xo."\n";

my $obj = Backup::ZFSonAWS->new($options);

if($options->{'function'} eq 'backup'){
	print STDERR "Doing backup\n";
	$obj->run_backup();
}
elsif($options->{'function'} eq 'recover'){
	print STDERR "Doing recovery, decrypting snapshot now.\n";
	$obj->decrypt_snapshot($options->{'checksumfile'},$options->{'snapshotfile'});
}


__END__

    ZFSonAWS is a program that automates backing up zfs snapshots onto AWS's S3.
    Copyright (C) 2015  Joel De Jesus

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.